spring:
  mvc:
    throw-exception-if-no-handler-found: true # 404 交给异常处理器处理
  profiles:
    active: dev
  resources:
    add-mappings: false

swagger:
  enabled: true
  title: oms-API
  description: API文档
  base-package: com.good0520.reactadmin.controller
  base-path: /**
  exclude-path: /error
  version: 1.9

server:
  port: 8080
---
spring:
  profiles: dev
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/reactadmin?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver

user:
  dir: F:\\personal\\code\\reactadmin-api